[window]

padding.x = 0
padding.y = 0

opacity = 0.9

[font]
#normal.style = "Regular"
#normal.family = "RobotoMonoNerdFontPropo"
#bold.family = "RobotoMonoNerdFontPropo"
#bold.style = "Bold"
#italic.family = "RobotoMonoNerdFontPropo"
#italic.style = "Italic"
#size = 11.0
normal.style = "Medium"
normal.family = "FiraCodeNerdFont"
bold.family = "FiraCodeNerdFont"
bold.style = "Bold"
italic.family = "FiraCodeNerdFont"
italic.style = "Italic"
size = 12.0

[colors]
primary.background = '0x06080c'
